"""
hyper parameter
"""


"""General Reinforcement Learning"""
REPLAY_MEMORY_SIZE = 2**22 # 4194304
ACTOR_EXPERIENCE_BUFFER_SIZE = 50
DISCOUNT_FACTOR = 0.997
Q_RESCALE_FACTOR = 1.0e-3

"""LSTM"""
BURN_IN_LENGTH = 40
SEQUENCE_LENGTH = 80
SEQUENCE_OVERLAP = 40
HIDDEN_STATE_DIMENSION = 512

"""PER: Prioritized Experience Replay"""
N_STEP_BOOTSTRAPING = 5
PRIORITY_EXPONENT = 0.9
IMPORTANCE_SAMPlING_EXPONENT = 0.6